In [1]:
import numpy as np
import csv
import pandas as pd
import os
import re
import string as st

In [55]:
# Function to remove @names and special character
def punc_clean(text):
    
    text= ' '.join(re.sub('(@[A-Za-z0-9_]+)|(&[A-Za-z0-9_]+)|([^0-9A-Za-z \t]) |(\w+:\/\/\S+)|(["“)#!?”(.%&$,*/;:<>=\/|^`{}~])' , " ", text).split())

    return text
        
def replace_name(data): 
    # Convert these @pfizer, @sinovac, @moderna_tx, @sputnikvaccine to normal form pfizer/sinovac/moderna/sputnik
    
    vaccine_dict = {"@pfizer": "pfizer",
                    "@sinovac": "sinovac",
                   "@moderna_tx": "moderna",
                   "@sputnikvaccine": "sputnik"}
    
    for index in range(len(data)):
        if "@pfizer" in data.loc[index, 'text']:
            vaccine_name = "@pfizer"
            replace_name = vaccine_dict[vaccine_name]
            data.loc[index, 'text'] = data.loc[index, 'text'].replace(vaccine_name, replace_name)

        if "@sinovac" in data.loc[index, 'text']:
            vaccine_name = "@sinovac"
            replace_name = vaccine_dict[vaccine_name]
            data.loc[index, 'text'] = data.loc[index, 'text'].replace(vaccine_name, replace_name)

        if "@moderna_tx" in data.loc[index, 'text']:
            vaccine_name = "@moderna_tx"
            replace_name = vaccine_dict[vaccine_name]
            data.loc[index, 'text'] = data.loc[index, 'text'].replace(vaccine_name, replace_name)

        if "@sputnikvaccine" in data.loc[index, 'text']:
            vaccine_name = "@sputnikvaccine"
            replace_name = vaccine_dict[vaccine_name]
            data.loc[index, 'text'] = data.loc[index, 'text'].replace(vaccine_name, replace_name)
            
    return data
    
def preprocess(path):
    path = os.path.join(path)
    data = pd.read_csv(path)
    
    data = replace_name(data)
    data['text'] = data['text'].apply(punc_clean)
    data['creation_date_time'] = data['creation_date_time'].apply(lambda x: x[:10])
    data["location"].fillna("No Location", inplace = True)
    
    has_duplicate = data.duplicated(subset=['text']).any()
    if has_duplicate:
        data.drop_duplicates(subset=['text'], inplace=True)
        
    return data

In [3]:
rapid_api_key = "48e2bca627mshf79e2f1948b6525p1b4bfajsned58b650da09"
BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAAI4ZQEAAAAA0CuD4%2BikWrOFi7myfncjcqXq2k8%3DjhlvJW1e8IMkuYcMeeCgqxpeoR66QgUcuUWeWRzf9Fobxmbn9L'

consumer_key = 'DZO4o46uebmsiM3QijUmbMj1J'
consumer_secret =    'jA9g5FaYIeXwrxTNrBM5zXqVJrjfqh1vEJzB0OwGyXfWvP2oN4'
access_token   = '1493791152159739904-wyTZRFyyLxYqhcYu13SAgJG528a5h2'
access_token_secret= 'Yf29sYInnBFgFzUo7Iy2wdrWPyGhkgjlMiNpHVjUPo8R9'

# Cleaning Covaxin Data, drop those bots data

In [108]:
# Crawled Covaxin csv file
covaxin_data = pd.read_csv("latest_data/Covaxin.csv")
covaxin_data

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502900173445296136,489184831,chovue,@CaptainXemo @WChrisNunn sigh.. youre the one...,0,0,NaN,2022-03-13 06:51:38+00:00
1,1502899182910119937,1389478820676210688,india_vac,BANGALORE: 44 slots found for age 18+!\nMar 13...,0,0,NaN,2022-03-13 06:47:42+00:00
2,1502897767315767298,1396115471703805953,CovidvaxDEL,North delhi has at least 2721 new slots availa...,0,0,"New Delhi, India",2022-03-13 06:42:04+00:00
3,1502897042334519301,489184831,chovue,@CaptainXemo @WChrisNunn jnj is based on adeno...,0,0,NaN,2022-03-13 06:39:12+00:00
4,1502896817314607107,3259025400,CaptainXemo,@chovue @WChrisNunn I don't care about covaxin...,0,0,NaN,2022-03-13 06:38:18+00:00
...,...,...,...,...,...,...,...,...
2307,1500404994268303361,1244878602094530560,Rajnees59765724,@PMOIndia when covaxin will be accepted in Ger...,0,0,NaN,2022-03-06 09:36:41+00:00
2308,1500403416719593472,1406895607680102404,vaxblr,18-44 #BBMP #Bengaluru #CovidVaccine Availabil...,1,0,"Bengaluru, India",2022-03-06 09:30:25+00:00
2309,1500401792856768512,1389478820676210688,india_vac,BANGALORE: 87 slots found for age 18+!\nMar 06...,0,0,NaN,2022-03-06 09:23:58+00:00
2310,1500396670374219779,4806490885,abyisnow,@DCEastSinghbhum Kindly arrange for Covaxin pr...,0,0,NaN,2022-03-06 09:03:36+00:00
2311,1500395799418589186,868380317039591425,Mayank_P_Grover,Saturday 5/3/22 #CoWIN_Dashboard &amp; @MoHFW_...,0,0,Deccans of India,2022-03-06 09:00:09+00:00

In [111]:
# Cleaned Covaxin
cleaned_covaxin = preprocess("latest_data/Covaxin.csv")
cleaned_covaxin

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502900173445296136,489184831,chovue,sigh youre the one in the dark If you truly do...,0,0,No Location,2022-03-13
1,1502899182910119937,1389478820676210688,india_vac,BANGALORE 44 slots found for age 18+ Mar 13 20...,0,0,No Location,2022-03-13
2,1502897767315767298,1396115471703805953,CovidvaxDEL,North delhi has at least 2721 new slots availa...,0,0,"New Delhi, India",2022-03-13
3,1502897042334519301,489184831,chovue,jnj is based on adenovirus tech Covaxin is bas...,0,0,No Location,2022-03-13
4,1502896817314607107,3259025400,CaptainXemo,I don't care about covaxin No do your own work...,0,0,No Location,2022-03-13
...,...,...,...,...,...,...,...,...
2307,1500404994268303361,1244878602094530560,Rajnees59765724,when covaxin will be accepted in Germany,0,0,No Location,2022-03-06
2308,1500403416719593472,1406895607680102404,vaxblr,18-44 BBMP Bengaluru CovidVaccine Availability...,1,0,"Bengaluru, India",2022-03-06
2309,1500401792856768512,1389478820676210688,india_vac,BANGALORE 87 slots found for age 18+ Mar 06 20...,0,0,No Location,2022-03-06
2310,1500396670374219779,4806490885,abyisnow,Kindly arrange for Covaxin precautionary dose ...,0,0,No Location,2022-03-06
2311,1500395799418589186,868380317039591425,Mayank_P_Grover,Saturday 5 3 22 CoWIN_Dashboard figures COVID1...,0,0,Deccans of India,2022-03-06

In [114]:
# We manually look at the data and realize that these few user are also a bot, therefore we want to filter it off

bot_list = ['CovidvaxDEL', 'BgmVaccineWatch', 'vaxblr', 'mybmcwardKW', 'india_vac', 'CovidvaxAMD', 'Mayank_P_Grover', 'mybmcWardRC', 'AverageJoe143', 'mybmcWardPN']
for username in bot_list:
    index = cleaned_covaxin[cleaned_covaxin.username == username].index
    cleaned_covaxin = cleaned_covaxin.drop(index)
cleaned_covaxin

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502900173445296136,489184831,chovue,sigh youre the one in the dark If you truly do...,0,0,No Location,2022-03-13
3,1502897042334519301,489184831,chovue,jnj is based on adenovirus tech Covaxin is bas...,0,0,No Location,2022-03-13
4,1502896817314607107,3259025400,CaptainXemo,I don't care about covaxin No do your own work...,0,0,No Location,2022-03-13
5,1502896236264771585,489184831,chovue,lol see my point exactly no buddy I am talking...,0,0,No Location,2022-03-13
6,1502895293242748930,1488528579910684684,Nii_Anue_Q,I’m with you all the way Covaxin is the foot i...,0,0,No Location,2022-03-13
...,...,...,...,...,...,...,...,...
2303,1500415255406600201,1242991317912879110,ahmed45231050,Scientists develop revolutionary cancer treatm...,0,0,Egypt,2022-03-06
2305,1500410050975649793,2516974466,NANDISHPATEL11,OCGN fda loves pfe and how else could they hel...,0,0,NYC,2022-03-06
2306,1500407697744687105,742211562,SakshiPost,US FDA Rejects Pediatric Use of India made Cov...,0,0,"Hyderabad, India",2022-03-06
2307,1500404994268303361,1244878602094530560,Rajnees59765724,when covaxin will be accepted in Germany,0,0,No Location,2022-03-06
2310,1500396670374219779,4806490885,abyisnow,Kindly arrange for Covaxin precautionary dose ...,0,0,No Location,2022-03-06

In [115]:
# Double check to see if any bot_list still in dataframe
for username in bot_list:
    print(cleaned_covaxin[cleaned_covaxin.username == username])

Empty DataFrame
Columns: [tweet_id, user_id, username, text, like_count, retweet_count, location, creation_date_time]
Index: []
Empty DataFrame
Columns: [tweet_id, user_id, username, text, like_count, retweet_count, location, creation_date_time]
Index: []
Empty DataFrame
Columns: [tweet_id, user_id, username, text, like_count, retweet_count, location, creation_date_time]
Index: []
Empty DataFrame
Columns: [tweet_id, user_id, username, text, like_count, retweet_count, location, creation_date_time]
Index: []
Empty DataFrame
Columns: [tweet_id, user_id, username, text, like_count, retweet_count, location, creation_date_time]
Index: []
Empty DataFrame
Columns: [tweet_id, user_id, username, text, like_count, retweet_count, location, creation_date_time]
Index: []
Empty DataFrame
Columns: [tweet_id, user_id, username, text, like_count, retweet_count, location, creation_date_time]
Index: []
Empty DataFrame
Columns: [tweet_id, user_id, username, text, like_count, retweet_count, location, creation_date_time]
Index: []
Empty DataFrame
Columns: [tweet_id, user_id, username, text, like_count, retweet_count, location, creation_date_time]
Index: []
Empty DataFrame
Columns: [tweet_id, user_id, username, text, like_count, retweet_count, location, creation_date_time]
Index: []

In [116]:
# Convert it to CSV
cleaned_covaxin.to_csv("Covaxin.csv", encoding='utf-8', index=False)

# Cleaning Moderna Data

In [117]:
# Crawled Moderna csv file
moderna_data = pd.read_csv("latest_data/Moderna.csv")
moderna_data

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502933227991822338,954212951497564160,TimmyTate66,@PianoGeek420 Double vaxxed w Pfizer and boost...,0,0,"Tennessee, USA",2022-03-13 09:02:59+00:00
1,1502933156655435777,1320331014124695552,TheosTina,@COORY4RYAN Moderna tried for 10 years to make...,0,0,NaN,2022-03-13 09:02:42+00:00
2,1502933102498181122,1466683352505749507,thetruthb3t0ld,@fedupmom12 @CensoredThinker Moderna and NIH w...,0,0,NaN,2022-03-13 09:02:29+00:00
3,1502932998215417856,26347653,AutomaticEarth,Debt Rattle March 13 2022 #ColdWar #FiatCurren...,0,0,Atlantic Ocean,2022-03-13 09:02:04+00:00
4,1502932679066624001,933450200361947136,MoveOverThere,@SueC00K @MailOnline That may not be the bigge...,0,0,UK,2022-03-13 09:00:48+00:00
...,...,...,...,...,...,...,...,...
2186,1502419212844744707,24195285,reinoe,Pfizer delists from SEC stock exchange in comp...,1,0,"Austin, TX",2022-03-11 23:00:28+00:00
2187,1502419180129337349,1463342010463494152,StockPlungeBot,Moderna Inc. (MRNA) plunges -9.37% between 202...,0,0,NaN,2022-03-11 23:00:20+00:00
2188,1502419129361264640,1439398920732307456,LeighDrummond,"What actual evidence of efficacy did Pfizer, M...",0,0,NaN,2022-03-11 23:00:08+00:00
2189,1502419018581479428,1102671699424825344,rubic3n,And so we come full circle\nWEF digital ID. So...,2,4,Moon,2022-03-11 22:59:42+00:00
2190,1502418485489463297,184153867,Hey_Hey_Joe,Moderna says data from Phase 2 study of mRNA f...,1,0,California,2022-03-11 22:57:35+00:00

In [118]:
# Cleaned Moderna
cleaned_moderna = preprocess("latest_data/Moderna.csv")
cleaned_moderna

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502933227991822338,954212951497564160,TimmyTate66,Double vaxxed w Pfizer and boosted Moderna No ...,0,0,"Tennessee, USA",2022-03-13
1,1502933156655435777,1320331014124695552,TheosTina,Moderna tried for 10 years to make mRNA techno...,0,0,No Location,2022-03-13
2,1502933102498181122,1466683352505749507,thetruthb3t0ld,Moderna and NIH were on to it first but Pfizer...,0,0,No Location,2022-03-13
3,1502932998215417856,26347653,AutomaticEarth,Debt Rattle March 13 2022 ColdWar FiatCurrenci...,0,0,Atlantic Ocean,2022-03-13
4,1502932679066624001,933450200361947136,MoveOverThere,That may not be the biggest scandal Pfizer and...,0,0,UK,2022-03-13
...,...,...,...,...,...,...,...,...
2186,1502419212844744707,24195285,reinoe,Pfizer delists from SEC stock exchange in comp...,1,0,"Austin, TX",2022-03-11
2187,1502419180129337349,1463342010463494152,StockPlungeBot,Moderna Inc MRNA plunges -9 37 between 2022-03...,0,0,No Location,2022-03-11
2188,1502419129361264640,1439398920732307456,LeighDrummond,What actual evidence of efficacy did Pfizer Mo...,0,0,No Location,2022-03-11
2189,1502419018581479428,1102671699424825344,rubic3n,And so we come full circle WEF digital ID Soci...,2,4,Moon,2022-03-11
2190,1502418485489463297,184153867,Hey_Hey_Joe,Moderna says data from Phase 2 study of mRNA f...,1,0,California,2022-03-11

In [119]:
# We manually look at the data and realize that these few user are also a bot, therefore we want to filter it off
bot_list = 'CarrieMyHart', 'VaxYork', 'PabloBach-OkMatar', 'VaxToronto', 'Jack78230841', '0Clout_4', 'GeneticLiberal', 'LucyMak6', 'roywinchester2', 'M157q_News_RSS',  'Hacker__News'

for username in bot_list:
    index = cleaned_moderna[cleaned_moderna.username == username].index
    cleaned_moderna = cleaned_moderna.drop(index)
cleaned_moderna

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502933227991822338,954212951497564160,TimmyTate66,Double vaxxed w Pfizer and boosted Moderna No ...,0,0,"Tennessee, USA",2022-03-13
1,1502933156655435777,1320331014124695552,TheosTina,Moderna tried for 10 years to make mRNA techno...,0,0,No Location,2022-03-13
2,1502933102498181122,1466683352505749507,thetruthb3t0ld,Moderna and NIH were on to it first but Pfizer...,0,0,No Location,2022-03-13
3,1502932998215417856,26347653,AutomaticEarth,Debt Rattle March 13 2022 ColdWar FiatCurrenci...,0,0,Atlantic Ocean,2022-03-13
4,1502932679066624001,933450200361947136,MoveOverThere,That may not be the biggest scandal Pfizer and...,0,0,UK,2022-03-13
...,...,...,...,...,...,...,...,...
2186,1502419212844744707,24195285,reinoe,Pfizer delists from SEC stock exchange in comp...,1,0,"Austin, TX",2022-03-11
2187,1502419180129337349,1463342010463494152,StockPlungeBot,Moderna Inc MRNA plunges -9 37 between 2022-03...,0,0,No Location,2022-03-11
2188,1502419129361264640,1439398920732307456,LeighDrummond,What actual evidence of efficacy did Pfizer Mo...,0,0,No Location,2022-03-11
2189,1502419018581479428,1102671699424825344,rubic3n,And so we come full circle WEF digital ID Soci...,2,4,Moon,2022-03-11
2190,1502418485489463297,184153867,Hey_Hey_Joe,Moderna says data from Phase 2 study of mRNA f...,1,0,California,2022-03-11

In [120]:
# Convert it to CSV
cleaned_moderna.to_csv("Moderna.csv", encoding='utf-8', index=False)

# Cleaning Sputnik data

In [121]:
# Crawled sputnik csv file
sputnik_data = pd.read_csv("latest_data/sputnik.csv")
sputnik_data

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502885637086609411,1455052349228023814,AndrewTRei1,"I will correctly remind people, yet again, tha...",2,1,NaN,2022-03-13 05:53:52+00:00
1,1502873976716107776,1498608701653102594,hamzaouihazim0,Local businessman first to take Sputnik V jab ...,0,0,NaN,2022-03-13 05:07:32+00:00
2,1502854289064173580,269110574,PolStuff,Could it be that Putin has gone insane from ta...,0,0,NaN,2022-03-13 03:49:18+00:00
3,1502846122129334276,1199410182230548480,cealaigi,@sbprme @MootIreland Anyway sanctions have alr...,2,1,NaN,2022-03-13 03:16:51+00:00
4,1502845215161602050,1502842093592580103,chicken_mcnug_,@ChuckCallesto Tucker admits to being Russian ...,1,1,NaN,2022-03-13 03:13:15+00:00
...,...,...,...,...,...,...,...,...
451,1500375433665257476,961331673152487426,Anymous84861064,@ShegaonkarSunil @conspiracytalk9 @greenboat P...,0,0,In orbit around G2 V Star.,2022-03-06 07:39:13+00:00
452,1500374067903275008,60444865,KittyOwner_Club,Indian Government Recommends Permission for Ph...,0,0,Thailand,2022-03-06 07:33:48+00:00
453,1500373492952612864,1334654385863811072,MasaruTogo,Indian Government Recommends Permission for Ph...,0,0,Tokyo,2022-03-06 07:31:30+00:00
454,1500372873948499978,34262462,SputnikInt,Indian Government Recommends Permission for Ph...,38,9,NaN,2022-03-06 07:29:03+00:00
455,1500367094235340801,878273096079335425,mariajt_,@_loistrange dear sputnik???? feeling recogniz...,0,0,NaN,2022-03-06 07:06:05+00:00

In [125]:
# Cleaned Sputnik
cleaned_sputnik = preprocess("latest_data/Sputnik.csv")
cleaned_sputnik

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502885637086609411,1455052349228023814,AndrewTRei1,I will correctly remind people yet again that ...,2,1,No Location,2022-03-13
1,1502873976716107776,1498608701653102594,hamzaouihazim0,Local businessman first to take Sputnik V jab,0,0,No Location,2022-03-13
2,1502854289064173580,269110574,PolStuff,Could it be that Putin has gone insane from ta...,0,0,No Location,2022-03-13
3,1502846122129334276,1199410182230548480,cealaigi,Anyway sanctions have already hit pharma with ...,2,1,No Location,2022-03-13
4,1502845215161602050,1502842093592580103,chicken_mcnug_,Tucker admits to being Russian sleeper cell af...,1,1,No Location,2022-03-13
...,...,...,...,...,...,...,...,...
450,1500379659128623105,1070238476719742976,AmNerdy,What If Sputnik V,0,0,"West Bengal, India",2022-03-06
451,1500375433665257476,961331673152487426,Anymous84861064,Pfizer had 45 000 volunteers across 3 continen...,0,0,In orbit around G2 V Star.,2022-03-06
452,1500374067903275008,60444865,KittyOwner_Club,Indian Government Recommends Permission for Ph...,0,0,Thailand,2022-03-06
453,1500373492952612864,1334654385863811072,MasaruTogo,Indian Government Recommends Permission for Ph...,0,0,Tokyo,2022-03-06
455,1500367094235340801,878273096079335425,mariajt_,dear sputnik feeling recognized with my sputni...,0,0,No Location,2022-03-06

In [127]:
bot_list = ['KittyOwner_Club', 'MasaruTogo', 'SputnikInt']
for username in bot_list:
    index = cleaned_sputnik[cleaned_sputnik.username == username].index
    cleaned_sputnik = cleaned_sputnik.drop(index)
cleaned_sputnik

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502885637086609411,1455052349228023814,AndrewTRei1,I will correctly remind people yet again that ...,2,1,No Location,2022-03-13
1,1502873976716107776,1498608701653102594,hamzaouihazim0,Local businessman first to take Sputnik V jab,0,0,No Location,2022-03-13
2,1502854289064173580,269110574,PolStuff,Could it be that Putin has gone insane from ta...,0,0,No Location,2022-03-13
3,1502846122129334276,1199410182230548480,cealaigi,Anyway sanctions have already hit pharma with ...,2,1,No Location,2022-03-13
4,1502845215161602050,1502842093592580103,chicken_mcnug_,Tucker admits to being Russian sleeper cell af...,1,1,No Location,2022-03-13
...,...,...,...,...,...,...,...,...
446,1500392995375370240,18159588,Oneindia,Govt panel recommends permission for phase 3 t...,0,1,India,2022-03-06
447,1500388454160642048,282664684,tutusaysso,Plus their vaccine diplomacy was also telling ...,1,0,No Location,2022-03-06
450,1500379659128623105,1070238476719742976,AmNerdy,What If Sputnik V,0,0,"West Bengal, India",2022-03-06
451,1500375433665257476,961331673152487426,Anymous84861064,Pfizer had 45 000 volunteers across 3 continen...,0,0,In orbit around G2 V Star.,2022-03-06
455,1500367094235340801,878273096079335425,mariajt_,dear sputnik feeling recognized with my sputni...,0,0,No Location,2022-03-06

In [128]:
# Convert it to CSV
cleaned_sputnik.to_csv("Sputnik.csv", encoding='utf-8', index=False)

# Cleaning general CovidVaccine data

In [54]:
# Crawled covidVaccine csv file
covidV_data = pd.read_csv("C:/Users/zappe/Desktop/NTUSTUFF/Year 3/Y3S2/Information Retrieval/CovidVaccine.csv")
covidV_data

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1504827607644360705,980850112527327234,PatientCV,"Dr. Martin Kulldorff, points out what he belie...",0,0,Sweden,2022-03-18 14:30:34+00:00
1,1504827600044101633,11733052,dougransom,Maybe tobacco companies should have to buy or ...,0,0,"Saanich, BC, Canada",2022-03-18 14:30:32+00:00
2,1504827583069769734,296107913,kartikeya_1975,Moderna has asked permission for 2nd booster s...,0,1,Delhi,2022-03-18 14:30:28+00:00
3,1504827573183909888,892100262,SandraHosford,@Storiesofinjury @the_Arkivist This was not a ...,0,0,NaN,2022-03-18 14:30:26+00:00
4,1504827562270281730,1035581018667982848,katamerica123,@Jerseyside @MdBreathe I don’t think vaccines ...,0,0,NaN,2022-03-18 14:30:23+00:00
...,...,...,...,...,...,...,...,...
2793,1504716053900939265,381312528,NEPABUZZ1,A woman in the Poconos says she is going to lo...,0,0,NEPA,2022-03-18 07:07:18+00:00
2794,1504715993431818242,2250875732,MuniGUARDNews,Idaho bill would ban COVID-19 vaccine mandates...,0,0,NaN,2022-03-18 07:07:03+00:00
2795,1504715829296132097,700817096,Adz91k,@TechARP @9NewsMelb It’s crazy the news will n...,0,0,AUSTRALIA,2022-03-18 07:06:24+00:00
2796,1504715749205630991,312271409,Reverend,"""Moderna CEO Stephane Bancel has sold $408 mil...",0,0,Lost and Found,2022-03-18 07:06:05+00:00
2797,1504715744759713797,15145034,abc27News,Speaker Nancy Pelosi said she's advised the Bi...,0,0,"Harrisburg, PA",2022-03-18 07:06:04+00:00

In [67]:
# Cleaned covidVaccine
cleaned_covidV = preprocess("C:/Users/zappe/Desktop/NTUSTUFF/Year 3/Y3S2/Information Retrieval/CovidVaccine.csv")
cleaned_covidV

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1504827607644360705,980850112527327234,PatientCV,Dr Martin Kulldorff points out what he believe...,0,0,Sweden,2022-03-18
1,1504827600044101633,11733052,dougransom,Maybe tobacco companies should have to buy or ...,0,0,"Saanich, BC, Canada",2022-03-18
2,1504827583069769734,296107913,kartikeya_1975,Moderna has asked permission for 2nd booster s...,0,1,Delhi,2022-03-18
3,1504827573183909888,892100262,SandraHosford,This was not a vaccine injury It was a COVID i...,0,0,No Location,2022-03-18
4,1504827562270281730,1035581018667982848,katamerica123,I don’t think vaccines should be advertised Bu...,0,0,No Location,2022-03-18
...,...,...,...,...,...,...,...,...
2791,1504716082032087041,381312528,NEPABUZZ1,A woman in the Poconos says she is going to lo...,0,0,NEPA,2022-03-18
2792,1504716068245364743,1279659380242354178,DryburghDotCom,Children are not and have never been at practi...,4,0,No Location,2022-03-18
2794,1504715993431818242,2250875732,MuniGUARDNews,Idaho bill would ban COVID-19 vaccine mandates...,0,0,No Location,2022-03-18
2795,1504715829296132097,700817096,Adz91k,It’s crazy the news will not even acknowledge ...,0,0,AUSTRALIA,2022-03-18
2796,1504715749205630991,312271409,Reverend,Moderna CEO Stephane Bancel has sold 408 milli...,0,0,Lost and Found,2022-03-18

In [68]:
bot_list = ['VaxBotSD', 'OIA_NZ', 'CovidvaxDEL', 'AJBlackston', 'CaoYi_MFA', 'ddnewskohima', 'FBastiat1', 'EconomicRenegad', 'QuealyJ', 'DinahParums', 'Supermarketguy1', 'StudiBressan_', 'Jamie83390459', 'pibchennai']
for username in bot_list:
    index = cleaned_covidV[cleaned_covidV.username == username].index
    cleaned_covidV = cleaned_covidV.drop(index)
cleaned_covidV

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1504827607644360705,980850112527327234,PatientCV,Dr Martin Kulldorff points out what he believe...,0,0,Sweden,2022-03-18
1,1504827600044101633,11733052,dougransom,Maybe tobacco companies should have to buy or ...,0,0,"Saanich, BC, Canada",2022-03-18
2,1504827583069769734,296107913,kartikeya_1975,Moderna has asked permission for 2nd booster s...,0,1,Delhi,2022-03-18
3,1504827573183909888,892100262,SandraHosford,This was not a vaccine injury It was a COVID i...,0,0,No Location,2022-03-18
4,1504827562270281730,1035581018667982848,katamerica123,I don’t think vaccines should be advertised Bu...,0,0,No Location,2022-03-18
...,...,...,...,...,...,...,...,...
2791,1504716082032087041,381312528,NEPABUZZ1,A woman in the Poconos says she is going to lo...,0,0,NEPA,2022-03-18
2792,1504716068245364743,1279659380242354178,DryburghDotCom,Children are not and have never been at practi...,4,0,No Location,2022-03-18
2794,1504715993431818242,2250875732,MuniGUARDNews,Idaho bill would ban COVID-19 vaccine mandates...,0,0,No Location,2022-03-18
2795,1504715829296132097,700817096,Adz91k,It’s crazy the news will not even acknowledge ...,0,0,AUSTRALIA,2022-03-18
2796,1504715749205630991,312271409,Reverend,Moderna CEO Stephane Bancel has sold 408 milli...,0,0,Lost and Found,2022-03-18

In [71]:
# Convert it to CSV
cleaned_covidV.to_csv("covidVaccine.csv", encoding='utf-8', index=False)

# Cleaning Pfizer data

In [136]:
# Crawled Pfizer csv file
pfizer_data = pd.read_csv("latest_data/Pfizer.csv")
pfizer_data

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502972060200574980,1241174508293312513,AngelaC11111101,The start was given! Wait... https://t.co/jIw...,0,0,NaN,2022-03-13 11:37:17+00:00
1,1502972032375754757,54516759,gladeolie,"Did #Pfizer #Vaccine #Documents Reveal 1,291 S...",0,0,cyberspace,2022-03-13 11:37:11+00:00
2,1502972013647994880,156451829,ctramseur,@jilevin Maybe it wasn't the same vaccine. Yes...,0,0,NaN,2022-03-13 11:37:06+00:00
3,1502972010892255235,1009545566290837504,SystemLordMoot,"@PianoGeek420 Got the triple Pfizer here, and ...",0,0,"England, United Kingdom",2022-03-13 11:37:05+00:00
4,1502971982673027075,1144167004892467200,DMB12445,Pfizer Buried Their Data in the Authorization ...,0,0,NaN,2022-03-13 11:36:59+00:00
...,...,...,...,...,...,...,...,...
4339,1502792330348216325,1431762585519595520,WaitingForPerot,@davey3483 @cheviotsue @Jerome95205658 @DagsWy...,0,0,NaN,2022-03-12 23:43:06+00:00
4340,1502792313021423616,3267880214,govtflu,@FOXLA Thanks Pfizer 😂,4,0,Earth,2022-03-12 23:43:02+00:00
4341,1502792277277790212,1456321142453673984,Tshepp_90,"Watch ""The Pfizer documents"" on YouTube https:...",1,0,NaN,2022-03-12 23:42:54+00:00
4342,1502792251721846786,1233974172696686593,Latifa2390,@opsoms @WHO @CDCgov @pfizer @FDA @EMA_news @O...,0,0,NaN,2022-03-12 23:42:47+00:00
4343,1502792197443313668,1356015027862401024,SenseReceptor,In a new viral video retired nurse Dr. John Ca...,1,0,NaN,2022-03-12 23:42:35+00:00

In [137]:
# Cleaned Pfizer
cleaned_pfizer = preprocess("latest_data/Pfizer.csv")
cleaned_pfizer

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502972060200574980,1241174508293312513,AngelaC11111101,The start was given Wait,0,0,No Location,2022-03-13
1,1502972032375754757,54516759,gladeolie,Did Pfizer Vaccine Documents Reveal 1 291 Side...,0,0,cyberspace,2022-03-13
2,1502972013647994880,156451829,ctramseur,Maybe it wasn't the same vaccine Yes I'm vacci...,0,0,No Location,2022-03-13
3,1502972010892255235,1009545566290837504,SystemLordMoot,Got the triple Pfizer here and my son who is t...,0,0,"England, United Kingdom",2022-03-13
4,1502971982673027075,1144167004892467200,DMB12445,Pfizer Buried Their Data in the Authorization ...,0,0,No Location,2022-03-13
...,...,...,...,...,...,...,...,...
4339,1502792330348216325,1431762585519595520,WaitingForPerot,Ok Fine Doesn’t matter My point is that the 1 ...,0,0,No Location,2022-03-12
4340,1502792313021423616,3267880214,govtflu,Thanks Pfizer 😂,4,0,Earth,2022-03-12
4341,1502792277277790212,1456321142453673984,Tshepp_90,Watch The Pfizer documents on YouTube,1,0,No Location,2022-03-12
4342,1502792251721846786,1233974172696686593,Latifa2390,pfizer President Donald J Trump interview OAN,0,0,No Location,2022-03-12
4343,1502792197443313668,1356015027862401024,SenseReceptor,In a new viral video retired nurse Dr John Cam...,1,0,No Location,2022-03-12

In [159]:
bot_list = ['CVaccinebot ', 'OIA_NZ', 'CovidvaxDEL', 'TechARP', 'maggmski88', 'VaxYork']
for username in bot_list:
    index = cleaned_pfizer[cleaned_pfizer.username == username].index
    cleaned_pfizer = cleaned_pfizer.drop(index)
cleaned_pfizer

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502972060200574980,1241174508293312513,AngelaC11111101,The start was given Wait,0,0,No Location,2022-03-13
1,1502972032375754757,54516759,gladeolie,Did Pfizer Vaccine Documents Reveal 1 291 Side...,0,0,cyberspace,2022-03-13
2,1502972013647994880,156451829,ctramseur,Maybe it wasn't the same vaccine Yes I'm vacci...,0,0,No Location,2022-03-13
3,1502972010892255235,1009545566290837504,SystemLordMoot,Got the triple Pfizer here and my son who is t...,0,0,"England, United Kingdom",2022-03-13
4,1502971982673027075,1144167004892467200,DMB12445,Pfizer Buried Their Data in the Authorization ...,0,0,No Location,2022-03-13
...,...,...,...,...,...,...,...,...
4339,1502792330348216325,1431762585519595520,WaitingForPerot,Ok Fine Doesn’t matter My point is that the 1 ...,0,0,No Location,2022-03-12
4340,1502792313021423616,3267880214,govtflu,Thanks Pfizer 😂,4,0,Earth,2022-03-12
4341,1502792277277790212,1456321142453673984,Tshepp_90,Watch The Pfizer documents on YouTube,1,0,No Location,2022-03-12
4342,1502792251721846786,1233974172696686593,Latifa2390,pfizer President Donald J Trump interview OAN,0,0,No Location,2022-03-12
4343,1502792197443313668,1356015027862401024,SenseReceptor,In a new viral video retired nurse Dr John Cam...,1,0,No Location,2022-03-12

In [161]:
# Convert it to CSV
cleaned_pfizer.to_csv("Pfizer.csv", encoding='utf-8', index=False)

# Cleaning Sinovac data

In [162]:
# Crawled Pfizer csv file
sinovac_data = pd.read_csv("latest_data/Sinovac.csv")
sinovac_data

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502959853635239940,84204994,mackattackone,@GreenEntreprise @chiu_francesca @tomgrundy @h...,0,0,NaN,2022-03-13 10:48:47+00:00
1,1502958946377740288,697443656706453504,RockTrolla,@DrEricDing Only 50% sinovac. \nIs it Right?,0,0,Ubicuo,2022-03-13 10:45:11+00:00
2,1502954945712033792,1231486724087222272,Transit_Jam,@FY4Chan @chiu_francesca The nursing homes pro...,0,0,Hong Kong,2022-03-13 10:29:17+00:00
3,1502953689643986944,742763463597031424,AFranzsen,@AswegenElvera @Bhekisisa_MG @HealthZA @miamal...,0,0,NaN,2022-03-13 10:24:17+00:00
4,1502951039183556609,969429491855618048,KCMO_Neal,@DrEricDing Could this just be due to the wani...,2,0,"Kansas City, MO",2022-03-13 10:13:45+00:00
...,...,...,...,...,...,...,...,...
906,1500446344443400193,1377836392902889472,foxosk1,@Hongkong_Bear @ThomasHHChan @primroseriordan ...,1,1,NaN,2022-03-06 12:21:00+00:00
907,1500440744233877504,1377836392902889472,foxosk1,@Hongkong_Bear @ThomasHHChan @primroseriordan ...,1,1,NaN,2022-03-06 11:58:44+00:00
908,1500439703786606597,462111175,Tonko35,"Telegram\nmRNA Death Tall\n\n💉☠ In China, a 14...",0,0,"Zagreb, Croatia",2022-03-06 11:54:36+00:00
909,1500438679029833729,975566592720306177,pharmaniaga_bhd,After the CoronaVac vaccine was granted condit...,1,1,"Selangor, Malaysia",2022-03-06 11:50:32+00:00
910,1500438515515277314,2238916212,WORLDOFBUZZ,Sinovac Vaccine Will Be Available For Kids Sta...,0,0,Malaysia,2022-03-06 11:49:53+00:00

In [163]:
# Cleaned Sinovac
cleaned_sinovac = preprocess("latest_data/sinovac.csv")
cleaned_sinovac

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502959853635239940,84204994,mackattackone,Then why is there an overwhelming sinovac upta...,0,0,No Location,2022-03-13
1,1502958946377740288,697443656706453504,RockTrolla,Only 50 sinovac Is it Right,0,0,Ubicuo,2022-03-13
2,1502954945712033792,1231486724087222272,Transit_Jam,The nursing homes provided Sinovac but delayed...,0,0,Hong Kong,2022-03-13
3,1502953689643986944,742763463597031424,AFranzsen,China attempted zero covid policy which succee...,0,0,No Location,2022-03-13
4,1502951039183556609,969429491855618048,KCMO_Neal,Could this just be due to the waning protectio...,2,0,"Kansas City, MO",2022-03-13
...,...,...,...,...,...,...,...,...
906,1500446344443400193,1377836392902889472,foxosk1,Should add I had 3 BioNTech shots myself but n...,1,1,No Location,2022-03-06
907,1500440744233877504,1377836392902889472,foxosk1,1 HK health care system has been under funded ...,1,1,No Location,2022-03-06
908,1500439703786606597,462111175,Tonko35,Telegram mRNA Death Tall 💉 In China a 14-year-...,0,0,"Zagreb, Croatia",2022-03-06
909,1500438679029833729,975566592720306177,pharmaniaga_bhd,After the CoronaVac vaccine was granted condit...,1,1,"Selangor, Malaysia",2022-03-06
910,1500438515515277314,2238916212,WORLDOFBUZZ,Sinovac Vaccine Will Be Available For Kids Sta...,0,0,Malaysia,2022-03-06

In [179]:
bot_list = ['kjoules', 'theSundaily', 'jone46404721', 'Unbelievable069']
for username in bot_list:
    index = cleaned_sinovac[cleaned_sinovac.username == username].index
    cleaned_sinovac = cleaned_sinovac.drop(index)
cleaned_sinovac

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502959853635239940,84204994,mackattackone,Then why is there an overwhelming sinovac upta...,0,0,No Location,2022-03-13
1,1502958946377740288,697443656706453504,RockTrolla,Only 50 sinovac Is it Right,0,0,Ubicuo,2022-03-13
2,1502954945712033792,1231486724087222272,Transit_Jam,The nursing homes provided Sinovac but delayed...,0,0,Hong Kong,2022-03-13
3,1502953689643986944,742763463597031424,AFranzsen,China attempted zero covid policy which succee...,0,0,No Location,2022-03-13
4,1502951039183556609,969429491855618048,KCMO_Neal,Could this just be due to the waning protectio...,2,0,"Kansas City, MO",2022-03-13
...,...,...,...,...,...,...,...,...
906,1500446344443400193,1377836392902889472,foxosk1,Should add I had 3 BioNTech shots myself but n...,1,1,No Location,2022-03-06
907,1500440744233877504,1377836392902889472,foxosk1,1 HK health care system has been under funded ...,1,1,No Location,2022-03-06
908,1500439703786606597,462111175,Tonko35,Telegram mRNA Death Tall 💉 In China a 14-year-...,0,0,"Zagreb, Croatia",2022-03-06
909,1500438679029833729,975566592720306177,pharmaniaga_bhd,After the CoronaVac vaccine was granted condit...,1,1,"Selangor, Malaysia",2022-03-06
910,1500438515515277314,2238916212,WORLDOFBUZZ,Sinovac Vaccine Will Be Available For Kids Sta...,0,0,Malaysia,2022-03-06

In [180]:
# Convert it to CSV
cleaned_sinovac.to_csv("Sinovac.csv", encoding='utf-8', index=False)

# Concatenate all different datas together to drop duplicates

In [80]:
df1 = pd.read_csv('cleaned_data v2.0/Covaxin.csv', header=None)
df2 = pd.read_csv('cleaned_data v2.0/CovidVaccine.csv', header=None)
df3 = pd.read_csv('cleaned_data v2.0/Moderna.csv', header=None)
df4 = pd.read_csv('cleaned_data v2.0/Pfizer.csv', header=None)
df5 = pd.read_csv('cleaned_data v2.0/Sinovac.csv', header=None)
df6 = pd.read_csv('cleaned_data v2.0/Sputnik.csv', header=None)

combined_data = pd.concat([df1, df2, df3, df4, df5, df6], ignore_index=True).drop_duplicates(0)
combined_data

,0,1,2,3,4,5,6,7
0,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
1,1502900173445296136,489184831,chovue,sigh youre the one in the dark If you truly do...,0,0,No Location,2022-03-13
2,1502897042334519301,489184831,chovue,jnj is based on adenovirus tech Covaxin is bas...,0,0,No Location,2022-03-13
3,1502896817314607107,3259025400,CaptainXemo,I don't care about covaxin No do your own work...,0,0,No Location,2022-03-13
4,1502896236264771585,489184831,chovue,lol see my point exactly no buddy I am talking...,0,0,No Location,2022-03-13
...,...,...,...,...,...,...,...,...
10539,1500392995375370240,18159588,Oneindia,Govt panel recommends permission for phase 3 t...,0,1,India,2022-03-06
10540,1500388454160642048,282664684,tutusaysso,Plus their vaccine diplomacy was also telling ...,1,0,No Location,2022-03-06
10541,1500379659128623105,1070238476719742976,AmNerdy,What If Sputnik V,0,0,"West Bengal, India",2022-03-06
10542,1500375433665257476,961331673152487426,Anymous84861064,Pfizer had 45 000 volunteers across 3 continen...,0,0,In orbit around G2 V Star.,2022-03-06
10543,1500367094235340801,878273096079335425,mariajt_,dear sputnik feeling recognized with my sputni...,0,0,No Location,2022-03-06

In [81]:
# Set the header name back
combined_data.rename(columns=combined_data.iloc[0], inplace = True)
combined_data.drop([0], inplace = True)
combined_data

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
1,1502900173445296136,489184831,chovue,sigh youre the one in the dark If you truly do...,0,0,No Location,2022-03-13
2,1502897042334519301,489184831,chovue,jnj is based on adenovirus tech Covaxin is bas...,0,0,No Location,2022-03-13
3,1502896817314607107,3259025400,CaptainXemo,I don't care about covaxin No do your own work...,0,0,No Location,2022-03-13
4,1502896236264771585,489184831,chovue,lol see my point exactly no buddy I am talking...,0,0,No Location,2022-03-13
5,1502895293242748930,1488528579910684684,Nii_Anue_Q,I’m with you all the way Covaxin is the foot i...,0,0,No Location,2022-03-13
...,...,...,...,...,...,...,...,...
10539,1500392995375370240,18159588,Oneindia,Govt panel recommends permission for phase 3 t...,0,1,India,2022-03-06
10540,1500388454160642048,282664684,tutusaysso,Plus their vaccine diplomacy was also telling ...,1,0,No Location,2022-03-06
10541,1500379659128623105,1070238476719742976,AmNerdy,What If Sputnik V,0,0,"West Bengal, India",2022-03-06
10542,1500375433665257476,961331673152487426,Anymous84861064,Pfizer had 45 000 volunteers across 3 continen...,0,0,In orbit around G2 V Star.,2022-03-06
10543,1500367094235340801,878273096079335425,mariajt_,dear sputnik feeling recognized with my sputni...,0,0,No Location,2022-03-06

In [83]:
pd.read_csv("Combined.csv")

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
0,1502900173445296136,489184831,chovue,sigh youre the one in the dark If you truly do...,0,0,No Location,2022-03-13
1,1502897042334519301,489184831,chovue,jnj is based on adenovirus tech Covaxin is bas...,0,0,No Location,2022-03-13
2,1502896817314607107,3259025400,CaptainXemo,I don't care about covaxin No do your own work...,0,0,No Location,2022-03-13
3,1502896236264771585,489184831,chovue,lol see my point exactly no buddy I am talking...,0,0,No Location,2022-03-13
4,1502895293242748930,1488528579910684684,Nii_Anue_Q,I’m with you all the way Covaxin is the foot i...,0,0,No Location,2022-03-13
...,...,...,...,...,...,...,...,...
10283,1500392995375370240,18159588,Oneindia,Govt panel recommends permission for phase 3 t...,0,1,India,2022-03-06
10284,1500388454160642048,282664684,tutusaysso,Plus their vaccine diplomacy was also telling ...,1,0,No Location,2022-03-06
10285,1500379659128623105,1070238476719742976,AmNerdy,What If Sputnik V,0,0,"West Bengal, India",2022-03-06
10286,1500375433665257476,961331673152487426,Anymous84861064,Pfizer had 45 000 volunteers across 3 continen...,0,0,In orbit around G2 V Star.,2022-03-06
10287,1500367094235340801,878273096079335425,mariajt_,dear sputnik feeling recognized with my sputni...,0,0,No Location,2022-03-06

In [89]:
# check to see if any duplicates 
combined_data.duplicated(subset=['text']).any()
combined_data.drop_duplicates(subset=['text'], inplace=True)

In [90]:
combined_data.duplicated(subset=['text']).any()

False

In [91]:
combined_data.to_csv("Combined.csv", index=False, encoding='utf-8')

In [1]:
# Use train test split to get 2000 test set for training for Classification 
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("Combined.csv")
train, test = train_test_split(df, test_size=0.1)
test

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
5464,1502454072607219712,1059908309057241089,LynnNMonteith1,I just love this Moderna is next Promise,3,0,No Location,2022-03-12
9950,1502244810161369089,1411866380987637762,ASEANNOWPH,DOH Filipinos hesitant to get Sputnik V COVID-...,0,0,Manila,2022-03-11
3124,1504755262523166729,439306202,cyre2067,So glad I didn't get the injections,0,0,America,2022-03-18
8592,1502811099544006656,1456425056272224259,pfizerlot,Edward Dowd Explains Bombshell ‘Fraud Charge r...,1,3,STOLEN KANATA,2022-03-13
6878,1502896683834695680,53079318,yummyroll,And I love it when the British Medical Journal...,0,0,No Location,2022-03-13
...,...,...,...,...,...,...,...,...
9510,1501616210840104970,1269356548641435648,gadboit,Or 🇭 have Sinovac VAED Or both I have faith se...,2,0,No Location,2022-03-09
1736,1504816821806911490,1193628520297062400,marcus08859455,More people with 3 doses of the vaccine curren...,0,0,No Location,2022-03-18
6324,1502933666233827333,1272202358,1427davisc,pfizer Pharma owns the journals They massage s...,2,0,"Milwaukee, WI",2022-03-13
8138,1502830402112610309,1490846378553012225,suko_tachi,pfizer He's in bed with BIG pharma getting mil...,0,0,No Location,2022-03-13
9311,1502290870724268036,1161474809261363200,Octogenarian_SH,And if you believe the false hope you get sino...,0,0,No Location,2022-03-11

In [3]:
test.to_csv("randomly_sample_01.csv", index=False, encoding='utf-8')

In [5]:
df = pd.read_csv("Combined.csv")
train, test2 = train_test_split(df, test_size=0.1)
test2

,tweet_id,user_id,username,text,like_count,retweet_count,location,creation_date_time
3275,1504745128363274243,1308355861966921729,TonyGriffonbrx,Not everyone that isn’t you is controlled oppo...,0,0,Edinburgh and Perthshire,2022-03-18
1829,1504812647006547972,169203141,PPDCRO,We have been at the forefront of enhancing imm...,0,1,Global,2022-03-18
10166,1500911250653552641,14157112,JoyShiningStar,Russia called out the Swiss listed Liechtenste...,1,0,SoCal/South Carolina,2022-03-07
278,1502260925721575427,1140643115541209088,mybmcWardMW,List of centers in the ward and related detail...,0,0,No Location,2022-03-11
5464,1502454072607219712,1059908309057241089,LynnNMonteith1,I just love this Moderna is next Promise,3,0,No Location,2022-03-12
...,...,...,...,...,...,...,...,...
6859,1502898347048321025,1171017902012674050,boitumelo_caleb,People have stopped taking it after reading ab...,0,0,No Location,2022-03-13
2057,1504805118956421129,337275737,CharnwoodBC,Loughborough Hospital have a Covid-19 walk-in ...,2,0,"Loughborough, Leicestershire",2022-03-18
6096,1502946361850970114,1264899714950062080,Boniswa63207956,It's a clone this one Nkosi yam If it knows ab...,0,0,No Location,2022-03-13
2187,1504800186316562433,2409032570,PeggyWi69224915,Massachusetts pharma company sues Moderna and ...,1,1,South Carolina,2022-03-18
5818,1502960431933050881,994330840829255680,Kohlrabi82,Now add Pfizer and Moderna please,2,0,"Kiel, Germany",2022-03-13

In [6]:
test2.to_csv("randomly_sample_02.csv", index=False, encoding='utf-8')