In [36]:
import csv
import pandas as pd

In [37]:
merged_combined = pd.read_csv("mycsvfileCombined.csv")
randomly_sampled = pd.read_csv("randomly_sample_01_train.csv")

In [38]:
merged_combined

          tweet_id  label                                         text_clean
0     1.387628e+18      2    offered vaccine wait  safe  best vaccine gÃ¢Â€...
1     1.392383e+18      2    rt aminamnzr   high upper  middle income cou...
2     1.392313e+18      1      starting   lyft begin providing ride codes...
3     1.392235e+18      0    rt gdc  bsimonward heck  extremely vulnerabl...
4     1.391884e+18      2    rt healthallamer  today found husband staff ...
...            ...    ...                                                ...
7535  1.370975e+18      1    swamy dr  swamy jee  people like covaxin vac...
7536  1.379827e+18      2    happy fully vaccinated covid   iÃ¢Â’m ready se...
7537  1.384789e+18      1    serum institute india announces cost covishi...
7538  1.382355e+18      0    batshitcrazy barrowfordhead bectully yesterd...
7539  1.380051e+18      1    smart sympathy attends oblong  educational f...

[7540 rows x 3 columns]

In [39]:
randomly_sampled = randomly_sampled[['tweet_id', 'text', 'sentiment']]
randomly_sampled.rename(columns={'text':'text_clean'}, inplace=True)
randomly_sampled.rename(columns={'sentiment':'label'}, inplace=True)

In [41]:
# Field 'attitude': 0 denotes positive attitude, 1 denotes neutral attitude, 2 denotes negative attitude
randomly_sampled['label'] = randomly_sampled['label'].replace({'POSITIVE':'0', 'Positive':'0'})
randomly_sampled['label'] = randomly_sampled['label'].replace({'NEUTRAL':'1', 'Neutral':'1'})
randomly_sampled['label'] = randomly_sampled['label'].replace({'NEGATIVE':'2', 'Negative':'2'})
randomly_sampled

          tweet_id                                         text_clean label
0     1.500000e+18           I just love this Moderna is next Promise     0
1     1.500000e+18  DOH Filipinos hesitant to get Sputnik V COVID-...     1
2     1.500000e+18                So glad I didn't get the injections     2
3     1.500000e+18  Edward Dowd Explains Bombshell â€˜Fraud Charge r...     1
4     1.500000e+18  And I love it when the British Medical Journal...     2
...            ...                                                ...   ...
1024  1.500000e+18  Or ðŸ‡­ have Sinovac VAED Or both I have faith se...     2
1025  1.500000e+18  More people with 3 doses of the vaccine curren...     2
1026  1.500000e+18  pfizer Pharma owns the journals They massage s...     2
1027  1.500000e+18  pfizer He's in bed with BIG pharma getting mil...     2
1028  1.500000e+18  And if you believe the false hope you get sino...     2

[1029 rows x 3 columns]

In [43]:
# swapping columns
randomly_sampled = randomly_sampled[['tweet_id','label','text_clean']]

In [44]:
randomly_sampled

          tweet_id label                                         text_clean
0     1.500000e+18     0           I just love this Moderna is next Promise
1     1.500000e+18     1  DOH Filipinos hesitant to get Sputnik V COVID-...
2     1.500000e+18     2                So glad I didn't get the injections
3     1.500000e+18     1  Edward Dowd Explains Bombshell â€˜Fraud Charge r...
4     1.500000e+18     2  And I love it when the British Medical Journal...
...            ...   ...                                                ...
1024  1.500000e+18     2  Or ðŸ‡­ have Sinovac VAED Or both I have faith se...
1025  1.500000e+18     2  More people with 3 doses of the vaccine curren...
1026  1.500000e+18     2  pfizer Pharma owns the journals They massage s...
1027  1.500000e+18     2  pfizer He's in bed with BIG pharma getting mil...
1028  1.500000e+18     2  And if you believe the false hope you get sino...

[1029 rows x 3 columns]

In [45]:
new_merged = merged_combined.append(randomly_sampled, ignore_index=True)

In [46]:
new_merged.to_csv("new_merged.csv", sep=',')

In [47]:
new_merged

          tweet_id label                                         text_clean
0     1.387628e+18     2    offered vaccine wait  safe  best vaccine gÃ¢Â€...
1     1.392383e+18     2    rt aminamnzr   high upper  middle income cou...
2     1.392313e+18     1      starting   lyft begin providing ride codes...
3     1.392235e+18     0    rt gdc  bsimonward heck  extremely vulnerabl...
4     1.391884e+18     2    rt healthallamer  today found husband staff ...
...            ...   ...                                                ...
8564  1.500000e+18     2  Or ðŸ‡­ have Sinovac VAED Or both I have faith se...
8565  1.500000e+18     2  More people with 3 doses of the vaccine curren...
8566  1.500000e+18     2  pfizer Pharma owns the journals They massage s...
8567  1.500000e+18     2  pfizer He's in bed with BIG pharma getting mil...
8568  1.500000e+18     2  And if you believe the false hope you get sino...

[8569 rows x 3 columns]